### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by LekovicMilos** [queicherius/i18next-po-loader#2]
Hi guys,

Is this plugin up to date, is it working with current React, npm and node?

Can someone share some tutorial how this plugin is being used? I cannot make it work on my code, don't know how to use it.

**Comment by queicherius** [comment]
I have not touched this in two years, but if webpack did not change it's interface it should still work.

This plugin does not care about React at all, you can just add it as a loader to your webpack config (e.g. like this)

```js
{
  test: /\.po$/, 
  loaders: ['i18next-po-loader']
}
```

and then import PO files like any other files, e.g. like this:

```js
const myPoFile = require('./de.po')
```

The PO files are then passed through https://github.com/i18next/i18next-gettext-converter, which turns them into JSON for use with https://www.i18next.com/

If you are starting out with translating your app, I would however nowadays recommend the excellent https://github.com/lingui/js-lingui instead, which has a cleaner interface (in my opinion) and better maintained tooling support.
