### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by gekkedev** [queicherius/i18next-po-loader#3]
According to [this weird Chinese mirror](https://cnpmjs.org/package/i18next-gettext-loader) you removed the package from npmjs.org. Why??  
Even though it's not actively maintained, you'll break other old software.

**Comment by queicherius** [comment]
The package is still available: https://www.npmjs.com/package/i18next-po-loader

**Comment by gekkedev** [comment]
My bad, though interesting: Searching for [the package](https://www.npmjs.com/search?q=i18next-gettext-loader) returns two results of which both are forks:  
![image](https://user-images.githubusercontent.com/17025257/110692710-ee92ee80-81e6-11eb-8930-50d67e0e4adb.png)
Were there any changes made to the package this year that could have (temporarily) removed it from cached search results? It seemed pretty severe as I was investigating why my CI I can't download the package anymore. Might be a problem on registry side then.

**Comment by queicherius** [comment]
The only change I made was deprecate it 3 years ago, but that's about it. Not sure why it would be hidden from search results for that, but it's possible. 🤷‍♂️
